image: node:10

stages:
- prepare
- build
- test
- deploy

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
  - node_modules/

prepare:
  stage: prepare
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build-ci
  artifacts:
    when: on_success
    paths:
      - dist/

registry:
  stage: deploy
  image: $CI_REGISTRY/craftmania/docker/node-docker:latest
  services:
    - docker:dind
  tags:
    - privileged
  dependencies:
    - build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

#test:general:
#  stage: test
#  script:
#    - npm run test

test:lint:
  stage: test
  script:
    - npm run lint

