image: node:8.9

stages:
- test
- build

cache:
  paths:
  - node_modules/

before_script:
  - npm cache rm --force
  - npm install

build:
  stage: build
  script:
    - npm run build

test:general:
  stage: test
  script:
    - npm run test

test:lint:
  stage: test
  script:
    - npm run lint

