image: node:10

stages:
- test
- build

cache:
  paths:
  - node_modules/

before_script:
  - npm cache rm --force
  - npm install

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - privileged
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

#test:general:
#  stage: test
#  script:
#    - npm run test

test:lint:
  stage: test
  script:
    - npm run lint

