version: "3"

services:
  craftapi:
    image: craftapi:latest
    #restart: always
    user: root
    container_name: craftapi
    volumes:
      - .env:/api/.env
    stop_grace_period: 7200s
    ports:
      - 3000:3000
