version: "3"

services:
  craftapi:
    image: git.craftmania.cz:4567/craftmania/craftapi-2:alpine
    #restart: always
    user: root
    container_name: craftapi
    volumes:
      - ./config/default.json:/api/config/default.json
    stop_grace_period: 7200s
    ports:
      - 3000:3000
