name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      commit:
        description: If the commit you want to test isn't the head of a branch, provide its SHA here
        required: false

env:
  HEAD_COMMIT: ${{ github.event.inputs.commit || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v3
        with:
          ref: ${{ env.HEAD_COMMIT }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: Build
        run: npm run build --if-present
