name: Packages

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Custom name for package'
        required: false
  push:
    tags:
      - '**'

env:
  CUSTOM_PACKAGE_NAME: ${{ github.event.inputs.name || github.ref_name }}

jobs:

  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_CONTAINER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        id: docker_build
        with:
          push: true
          file: ./Dockerfile
          build-args: |
            BUILD_VERSION=${{ github.ref_name }}
            COMMIT_HASH=${{ github.sha }}
            REGISTRY_TOKEN=${{ secrets.PAT_CONTAINER_TOKEN }}
          tags: |
            ghcr.io/craftmania-cz/craftapi:latest
            ghcr.io/craftmania-cz/craftapi:${{ env.CUSTOM_PACKAGE_NAME }}
